### PR TITLE
Feature footer newsletter

### PR DESCRIPTION
**Pull request by megaboy101**
This adds a newsletter form to the page footer, and includes email validation, 500 server error feedback, and locking a user from resubmitting their email after a successful submission.

All emails are currently kept as documents in Firebase under `/newsletterSubscribers`

### CODE REVIEW

**Comment by megaboy101** [comment]
@Smudded I follow you on the form field and title, but what part of the form are you referring to when you say the description?

**Comment by Smudded** [comment]
The description would be the part that says "Stay notified for regular updates on upcoming events and ways to get involved"

Also, just realized there's multiple commits in here. If you could squash all of these into a single commit that would be much appreciated. Just makes it easier to make PRs single commits so we don't end up with bloated PRs

**Comment by megaboy101** [comment]
@Smudded Ah ok I follow you now, and yes I can also do that.

**Comment by megaboy101** [comment]
@Smudded Ok so I refactored out the newsletter component and I am ready to squash all these commits, but I am a bit stuck and am curious about your thoughts. I've never gone through the process of squashing commits before, and since midway through the commits for this feature there is a merge in from master, squashing the commits would also include unrelated commits from what I can gather. Is there a way to resolve this?

**Comment by Smudded** [comment]
Ahhh, right. Is the merge commit a result of you pulling? Whenever you pull you should always be rebasing rather than merging. That command looks like... `git pull --rebase origin master`

**Comment by Smudded** [comment]
Due to the merge commit we probably don't need to squash these ones.

**Comment by megaboy101** [comment]
Ok gotcha. Ya now that you mention it I'm kinda scratching my head why I made that decision since usually I always rebase my commits. In any case though sounds good, then is there anything else I need to take care of or is this good to merge?

**Pull request merged**
