### PR TITLE
Added filter on companies page for size & industry

### PR DESCRIPTION
**Pull request by megaboy101**
This adds the filtering component found on the jobs page to the companies page, and has dropdowns to filter by industry, or company size. In addition, this refactors a lot of the styles for the filter component and filter logic into its own dedicated component.

It was noted in Notion that companies should now have designated integer sizes to allow for filtering. However, given all the places the data is used it ended up being easier to work around strings than have to hunt down every bug in the client and admin portal created by changing the data type, as well as having to change every entry in Firebase by hand. Instead, the filter works by scanning through all the companies, and creating a set of all unique size options found. Those values are then used to filter, that way if any other unique company sizes are added in the future, the logic will still hold.

### CODE REVIEW

**Comment by Smudded** [comment]
Hm, I think my beef with that company size filter is that it just doesn't work in the way that is easiest or most intuitive. Say there's a company with a size property of 90-110 employees, and one with 95-105.  If I want to view all companies with around 100 employees I can't do that. I'd have to filter to those companies separately. There will be two separate items in the filter that cover mostly the same range, and are not inclusive of each other. Unfortunately, I think we need to change the data type to a number or a two number range so we can actually use math on it.

**Comment by megaboy101** [comment]
Hmm I see your point. If employee count was changed to a hard number then rather than a range, I image we could store min and max size values as a 2-item list/tuple. We could then have 2 input values next to each other for someone in the admin client to input the min and max? And then I imagine the frontend would just have ranged filters for company employee counts like <10, 10-50, 50-100, 100-500, 500+. Another alternative would be locking the range a company can input as their size into a predefined list of string values (like the options above). That may be hard to enforce though even if it is locked behind the admin client, and it wouldn't let us do any math on the values either.

**Comment by Smudded** [comment]
I think I'd be okay with locked ranges that are still just a string. We'll convert the field on the backend to be a dropdown with predefined buckets and convert the current companies to use those.

**Comment by Smudded** [comment]
Testing for Slack integration.

**Comment by megaboy101** [comment]
Updated to include changing the employee count input to a select element in the admin portal.

**Pull request merged**
